apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- route.yaml

images:
- name: wordpress
  newName: quay.io/rh_ee_lupanza/demo-wordpress
  newTag: bcd90a0f3c288a94ba38b9ff5f3ed735f5bfe06b
